# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - ProjView

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Build React Application
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install React app dependencies
        run: npm install
        working-directory: ./FrontEnd  # Change to your React app folder

      - name: Build React app
        run: npm run build
        working-directory: ./FrontEnd  # Change to your React app folder
        env:  # Pass the secrets as environment variables
          CI: false  # Temporarily set CI to false to bypass warnings as errors

      - name: Copy React build to Spring Boot static folder
        run: |
          echo "Copying React build files to Spring Boot static folder"
          rm -rf ./src/main/resources/static/*  # Clear existing static files
          cp -r ./FrontEnd/build/* ./src/main/resources/static/  # Copy new build files
        shell: bash  # Use bash to ensure compatibility with Unix commands

      - name: Upload React build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: './FrontEnd/build/**/*'  # Adjust path to your React build output

      - name: Build with Maven
        run: mvn clean install
        # Uncomment and set the environment variables if needed
        # env:
        #   SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
        #   SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        #   SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        #   JIRA_CLIENT_ID: ${{ secrets.JIRA_CLIENT_ID }}
        #   JIRA_SECRET: ${{ secrets.JIRA_SECRET }}
        #   JIRA_REDIRECT_URI: ${{ secrets.JIRA_REDIRECT_URI }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C10121DE7B324BA5AB0197847D750FC4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C06210E4DC154DEF82F0CA876E351DDA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A0357E409AF64ACFAA17EEEFFE3B3F13 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projview'
          slot-name: 'Production'
          package: '${{ github.workspace }}/target/*.jar'  # Ensure correct path to JAR file
